services:
  php:
    build:
      dockerfile: ./docker/php.Dockerfile
      context: .
    volumes:
      - .:/app
    user: 1000:1000
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - PHP_IDE_CONFIG=serverName=app.loc
